name: ChakaCraftMC
version: 1.0.0-B5
main: cf.chakacraftmc.plugin.ChakaCraftMC
commands:
  ccmc:
    description: The main command.
    usage: /<command>
permissions:
  ccmc.admin:
    description: Admins Node
    children:
      ccmc.mod: true
      ccmc.player: true
  ccmc.mod:
    description: Moderator Node
    children:
      ccmc.player: true
  ccmc.player:
    description: Player Node
    children:
      ccmc.cmd: true